name: make-lint
on: push

jobs:
  make-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make-install
        run: |
             pip install poetry
             poetry install
        env: PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring  
      - name: make-lint
        run: |
             make lint
     
